Repository anifriends/Anifriends-Backend, pull requests merged in 2023-12, with the labels that each got.

#382 fix: 모집 마감된 봉사 신청 시 응답 상태 코드를 수정한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/exception/ApplicantCanNotApplyException.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/test/java/com/clova/anifriends/domain/applicant/ApplicantTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
Labels: 🐞 Bug

#388 fix: 내(보호소)가 작성한 봉사 모집글 검색 시 키워드 검색이 되지 않는 문제를 수정한다.
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
Labels: 🐞 Bug

#393 fix: 리뷰 업데이트 시 이미지 컬렉션에 대한 참조를 변경하지 않도록 수정한다.
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
Labels: 🐞 Bug

#397 fix: 리뷰 등록 api 요청 변수 이름을 수정한다.
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/request/RegisterReviewRequest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
Labels: 🐞 Bug

#390 refactor: 테스트 시 애플리케이션 컨텍스트 초기화를 줄여 테스트 속도를 개선한다.
  src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java
  src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/global/scheduler/NotifyScheduler.java
  src/main/java/com/clova/anifriends/global/scheduler/ServiceScheduler.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/base/BaseSchedulerTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/global/scheduler/NotifySchedulerTest.java
  src/test/java/com/clova/anifriends/global/scheduler/ServiceSchedulerTest.java
  src/test/resources/application.yml
Labels: 🔨 Refactor

#400 fix: 봉사 모집 조회 시 이미지를 left join 하도록 수정한다.
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
Labels: 🐞 Bug

#402 fix: 이미지 확장자에 .webp를 추가한다.
  src/main/java/com/clova/anifriends/global/image/S3Service.java
Labels: 🐞 Bug

#406 fix: 내(보호소)가 받은 리뷰 목록 조회시 데이터 조회가 되지 않는 문제를 수정한다.
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/repository/response/FindShelterReviewResultV2.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: 🐞 Bug

#410 fix: 봉사 신청자 목록 조회 시 봉사자의 봉사 횟수가 실제 횟수와 일치하지 않는 부분을 수정한다.
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/resources/application.yml
Labels: 🐞 Bug

#412 fix: FindShelterReviewResponse에서 VolunteerReviewCount 이름을 수정한다.
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: 🐞 Bug

#416 refactor: 봉사자가 작성한 후기 개수를 반정규화한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/vo/VolunteerReviewCount.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/vo/VolunteerReviewCountTest.java
Labels: 🔨 Refactor

#422 fix: 내(보호소)가 받은 리뷰 목록 조회 batchSize가 적용되지 않는 문제를 수정한다.
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
Labels: 🐞 Bug

#428 refactor: 서비스 로직의 캐시 리포지토리 의존성을 역전시킨다.
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalCacheRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRedisRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentCacheRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRedisRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheService.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/global/event/CacheWarmer.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRedisRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 🔨 Refactor

#430 docs: readme에 api 명세, 이슈/해결 글을 추가한다.
  README.md
Labels: 📝 Docs

#433 refactor: 내(보호소)가 받은 봉사 후기 목록 조회 일대다 페이지네이션 쿼리를 개선한다.
  src/main/java/com/clova/anifriends/domain/common/dto/PageInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindShelterRecruitmentsResponse.java
  src/main/java/com/clova/anifriends/domain/review/ReviewImage.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindVolunteerReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/review/repository/response/FindShelterReviewByShelterResult.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewMapper.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/support/ReviewDtoFixture.java
Labels: 🔨 Refactor

#439 refactor: AOP 순서를 지정한다.
  src/main/java/com/clova/anifriends/global/aspect/DataIntegrityAspect.java
  src/main/java/com/clova/anifriends/global/aspect/LogAspect.java
  src/test/resources/application.yml
Labels: 🔨 Refactor

#440 refactor: 보호 동물 목록 조회 쿼리를 개선한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java
  src/main/java/com/clova/anifriends/domain/animal/mapper/AnimalMapper.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalMapper.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
Labels: 🔨 Refactor

#442 feat: 결제 실패 시 결제 상태를 `ABORTED` 로 변경한다.
  README.md
  src/main/java/com/clova/anifriends/domain/payment/service/PaymentService.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/payment/service/PaymentIntegrationTest.java
Labels: ✨ Feat

#443 fix: 봉사자 이미지 업데이트 시 기존 이미지 엔티티가 제거되지 않는 문제를 수정한다.
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/ShelterImage.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
Labels: 🐞 Bug

#445 refactor: S3 에서 이미지를 삭제하는 로직을 비동기적으로 동작하도록 수정한다.
  src/main/java/com/clova/anifriends/domain/common/event/ImageDeletionListener.java
  src/main/java/com/clova/anifriends/global/config/AsyncConfig.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
Labels: 🔨 Refactor
