Repository anifriends/Anifriends-Backend, pull requests merged in 2023-11, with the labels that each got.

#43 fix: 소나클라우드 CI를 수정한다.
  .github/workflows/ci.yml
  .github/workflows/sonar-cloud.yml
  build.gradle
  lombok.config
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/AnimalImage.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalBreed.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalInformation.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalName.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalNeutered.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalWeight.java
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/RecruitmentImage.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentContent.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentDeadlineInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTime.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTitle.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/ReviewImage.java
  src/main/java/com/clova/anifriends/domain/review/wrapper/ReviewContent.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/ShelterImage.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfo.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterEmail.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterName.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfo.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/test/java/com/clova/anifriends/domain/animal/AnimalImageTest.java
  src/test/java/com/clova/anifriends/domain/animal/AnimalTest.java
  src/test/java/com/clova/anifriends/domain/applicant/ApplicantTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentImageTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/review/ReviewImageTest.java
  src/test/java/com/clova/anifriends/domain/review/ReviewTest.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterImageTest.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerImageTest.java
Labels: 🐞 Bug

#41 feat: 사용자 인증을 위한 jwt 인증 프로세스를 구현한다.
  build.gradle
  src/main/java/com/clova/anifriends/domain/auth/RefreshToken.java
  src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthentication.java
  src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProvider.java
  src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
  src/main/java/com/clova/anifriends/domain/auth/controller/request/LoginRequest.java
  src/main/java/com/clova/anifriends/domain/auth/exception/AuthAuthenticationException.java
  src/main/java/com/clova/anifriends/domain/auth/exception/ExpiredAccessTokenException.java
  src/main/java/com/clova/anifriends/domain/auth/exception/ExpiredRefreshTokenException.java
  src/main/java/com/clova/anifriends/domain/auth/exception/InvalidJwtException.java
  src/main/java/com/clova/anifriends/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/JJwtProvider.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/JwtProvider.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/UserRole.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/response/CustomClaims.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/response/UserToken.java
  src/main/java/com/clova/anifriends/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/clova/anifriends/domain/auth/resolver/LoginUser.java
  src/main/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolver.java
  src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
  src/main/java/com/clova/anifriends/domain/auth/service/response/TokenResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/repository/ShelterRepository.java
  src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/config/WebMvcConfig.java
  src/main/java/com/clova/anifriends/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/clova/anifriends/AnifriendsApplicationTests.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolverTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserTestController.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
Labels: ✨ Feat

#44 feat: 봉사 모집글 상세 조회 로직을 구현한다.
  coverage-exclude.anifriends
  src/main/java/com/clova/anifriends/domain/common/BaseTimeEntity.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/RecruitmentImage.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/exception/RecruitmentNotFoundException.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/support/fixture/ShelterFixture.java
Labels: ✨ Feat

#46 feat: 봉사자 마이페이지 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerMyPageResponse.java
  src/main/java/com/clova/anifriends/domain/volunteer/exception/VolunteerNotFoundException.java
  src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerImageRepository.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerImageTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerImageFixture.java
Labels: ✨ Feat

#51 feat: 마이페이지 조회 로직을 구현한다. (보호소)
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/FindShelterMyPageResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterName.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolverTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
Labels: ✨ Feat

#47 feat: 봉사 모집글 등록 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/RegisterRecruitmentRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/RegisterRecruitmentResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/exception/RecruitmentBadRequestException.java
  src/main/java/com/clova/anifriends/domain/recruitment/mapper/RecruitmentMapper.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentContent.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTitle.java
  src/main/java/com/clova/anifriends/domain/shelter/exception/ShelterNotFoundException.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/resources/application.yml
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolverTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentContentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfoTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTitleTest.java
  src/test/java/com/clova/anifriends/global/exception/GlobalExceptionHandlerTest.java
Labels: ✨ Feat

#54 feat: 봉사자 프로필 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerProfileResponse.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterEmailTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterNameTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPasswordTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfoTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
Labels: ✨ Feat

#55 feat: 봉사 신청 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/exception/ApplicantBadRequestException.java
  src/main/java/com/clova/anifriends/domain/applicant/exception/ApplicantConflictException.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/ApplicantTest.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feat

#56 feat: 보호 동물 등록 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/RegisterAnimalRequest.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/RegisterAnimalResponse.java
  src/main/java/com/clova/anifriends/domain/animal/exception/AnimalBadRequestException.java
  src/main/java/com/clova/anifriends/domain/animal/mapper/AnimalMapper.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalImageRepository.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalBreed.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalInformation.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalName.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalWeight.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/resources/application.yml
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/AnimalTest.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalFixture.java
  src/test/java/com/clova/anifriends/domain/animal/wrapper/AnimalBreedTest.java
  src/test/java/com/clova/anifriends/domain/animal/wrapper/AnimalInformationTest.java
  src/test/java/com/clova/anifriends/domain/animal/wrapper/AnimalNameTest.java
  src/test/java/com/clova/anifriends/domain/animal/wrapper/AnimalWeightTest.java
Labels: ✨ Feat

#61 fix: 봉사자 마이페이지에서 imageUrl은 optional이다.
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: 🐞 Bug

#76 feat: 보호소에서 모집글을 조회 및 검색한다.
  src/main/java/com/clova/anifriends/domain/common/dto/PageInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/global/config/QueryDslConfig.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
Labels: ✨ Feat

#71 feat: 봉사자에서 모집글을 조회 및 검색한다.
  build.gradle
  src/main/java/com/clova/anifriends/domain/common/PageInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByVolunteerRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentDetailByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/global/config/QueryDslConfig.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
Labels: ✨ Feat

#82 feat: 봉사 승인자 리스트 조회 로직을 구현
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsApprovedResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/applicant/support/ApplicantFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
Labels: ✨ Feat

#75 feat: 보호소의 후기 리스트 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/common/BaseTimeEntity.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
Labels: ✨ Feat

#84 feat: 봉사자가 완료한 봉사 모집글 리스트 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindCompletedRecruitmentsResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/support/ShelterFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
Labels: ✨ Feat

#72 feat: 봉사 후기 작성시 보호소 정보 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindShelterSimpleResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: ✨ Feat

#90 fix: controller에서 service로 인자를 보낼 때 RequestDTO 자체로 보내지 않는다.
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumber.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumberTest.java
Labels: 🐞 Bug

#85 feat: 봉사 후기 작성 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/request/RegisterReviewRequest.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindReviewResponse.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/review/exception/ApplicantNotFoundException.java
  src/main/java/com/clova/anifriends/domain/review/exception/ReviewAuthorizationException.java
  src/main/java/com/clova/anifriends/domain/review/exception/ReviewBadRequestException.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/review/wrapper/ReviewContent.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/applicant/support/ApplicantFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/review/ReviewTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/support/ReviewDtoFixture.java
  src/test/java/com/clova/anifriends/domain/review/support/ReviewFixture.java
  src/test/java/com/clova/anifriends/domain/review/wrapper/ReviewContentTest.java
Labels: ✨ Feat

#86 refactor: EnumType 인터페이스에서 사용하지 않는 메서드를 삭제한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalActive.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalGender.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalType.java
  src/main/java/com/clova/anifriends/domain/applicant/wrapper/ApplicantStatus.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/UserRole.java
  src/main/java/com/clova/anifriends/domain/common/EnumType.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerGender.java
  src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
  src/test/java/com/clova/anifriends/docs/enumtype/EnumDocsController.java
  src/test/java/com/clova/anifriends/docs/enumtype/EnumDocumentationTest.java
  src/test/java/com/clova/anifriends/docs/enumtype/TestEnum.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalFixture.java
Labels: 🔨 Refactor

#83 feat: 보호소에 달린 봉사 모집글 리스트 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterIdResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
Labels: ✨ Feat

#89 feat: 봉사 모집글 작성시 이미지 url을 함께 받을 수 있도록 변경한다.
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/mapper/RecruitmentMapper.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: ✨ Feat

#92 feat: spring security 권한 필터 설정을 적용한다.
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
Labels: ✨ Feat

#93 feat: 봉사자가 작성한 후기 리스트 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindVolunteerReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feat

#95 fix: 보호소의 모집글 상세조회에서 보호소 Id 와 모집글 Id 로 조회하도록 변경
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 🐞 Bug

#101 fix: 보호소에 달린 후기 리스트 조회 api 에서 봉사자의 리뷰 개수를 잘못 가져오는 로직을 수정한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerMyPageResponse.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: 🐞 Bug

#104 fix: CodeDeploy permission denied를 해결한다.
  appspec.yml
Labels: 🐞 Bug

#87 feat: 봉사자가 신청한 봉사 리스트 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/wrapper/ReviewContentTest.java
Labels: ✨ Feat

#97 feat: 보호소에 달린 후기 리스트 조회 로직을 구현한다. (봉사자 입장)
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feat

#137 feat: 로그인 시 리프레시 토큰을 쿠키에 담아서 응답한다.
  src/main/java/com/clova/anifriends/domain/auth/RefreshToken.java
  src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
  src/main/java/com/clova/anifriends/domain/auth/controller/response/LoginResponse.java
  src/main/java/com/clova/anifriends/domain/auth/exception/AuthNotFoundException.java
  src/main/java/com/clova/anifriends/domain/auth/exception/ExpiredAccessTokenException.java
  src/main/java/com/clova/anifriends/domain/auth/exception/ExpiredRefreshTokenException.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/JJwtProvider.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/JwtProvider.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/response/TokenResponse.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/response/UserToken.java
  src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
  src/main/java/com/clova/anifriends/domain/auth/service/response/TokenResponse.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
  src/test/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
  src/test/java/com/clova/anifriends/domain/auth/support/MockPasswordEncode.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/global/exception/ExceptionController.java
Labels: ✨ Feat

#143 feat: 보호소 입장에서 보호 동물 조회 & 검색 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/animal/AnimalAge.java
  src/main/java/com/clova/anifriends/domain/animal/AnimalSize.java
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feat

#140 feat: 회원가입(보호소) 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/shelter/controller/RegisterShelterRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/exception/ShelterBadRequestException.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfo.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfo.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfoTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPasswordTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfoTest.java
Labels: ✨ Feat

#146 refactor: 봉사 모집글 등록(보호소)를 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
Labels: 🔨 Refactor

#150 refactor: 봉사자 프로필 조회(공통)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerProfileResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: 🔨 Refactor

#148 refactor: 봉사 승인자 리스트 조회(보호소)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsApprovedResponse.java
Labels: 🔨 Refactor

#145 feat: 보호 동물 검색 조회 로직을 구현한다.(봉사자)
  src/main/java/com/clova/anifriends/domain/animal/AnimalAge.java
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByVolunteerRequest.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
Labels: ✨ Feat

#149 fix: 배포시 restDocs 정적 문서에 접근할 수 없는 문제를 해결한다.
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
Labels: 🐞 Bug

#152 refactor: 모집글 검색(봉사자)를 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByVolunteerResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 🔨 Refactor

#153 refactor: 봉사 후기 상세 조회(봉사자)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindReviewResponse.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
Labels: 🔨 Refactor

#154 refactor: 봉사자가 완료한 봉사 모집글 리스트 조회(공통)을 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindCompletedRecruitmentsResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
Labels: 🔨 Refactor

#157 refactor: 보호동물 상세(공통)를 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalDetail.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalDtoFixture.java
Labels: 🔨 Refactor

#159 refactor: 보호소에 달린 후기 리스트 조회(봉사자)를 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByVolunteerResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
Labels: 🔨 Refactor

#155 refactor: 보호소 간단 정보 조회(봉사자)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindShelterSimpleResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/FindShelterSimpleByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/RegisterShelterRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
Labels: 🔨 Refactor

#161 refactor: 봉사자가 신청한 봉사 리스트 조회(봉사자)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
Labels: 🔨 Refactor

#160 feat: 액세스 토큰 전송시 perfix Bearer를 추가한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/auth/LoginUser.java
  src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProvider.java
  src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
  src/main/java/com/clova/anifriends/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/clova/anifriends/domain/auth/dto/response/CustomClaims.java
  src/main/java/com/clova/anifriends/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/clova/anifriends/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/clova/anifriends/domain/auth/exception/InvalidJwtException.java
  src/main/java/com/clova/anifriends/domain/auth/jwt/JwtProvider.java
  src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/config/WebMvcConfig.java
  src/main/java/com/clova/anifriends/global/jwt/JJwtProvider.java
  src/main/java/com/clova/anifriends/global/web/argumentresolver/LoginUserArgumentResolver.java
  src/main/java/com/clova/anifriends/global/web/filter/JwtAuthenticationFilter.java
  src/test/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserTestController.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
Labels: ✨ Feat

#163 refactor: 보호소에 달린 후기 리스트 조회(보호소)를 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#164 refactor: 봉사자가 작성한 후기 리스트 조회(공통)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindVolunteerReviewsResponse.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
Labels: 🔨 Refactor

#167 refactor: 마이페이지 조회(봉사자)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerMyPageResponse.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java
Labels: 🔨 Refactor

#168 refactor: 모집글 조회 & 검색(보호소)를 명세에 맞게 수정한다.
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentDtoFixture.java
Labels: 🔨 Refactor

#169 feat: 봉사 신청 현황 조회 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/applicant/wrapper/ApplicantStatus.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
Labels: ✨ Feat

#166 refactor: 마이페이지 조회(보호소)를 명세에 맞게 수정한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/FindShelterMyPageResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
Labels: 🔨 Refactor

#172 feat: 보호소 주소 공개 여부 수정 로직을 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
  src/main/java/com/clova/anifriends/domain/common/CustomPasswordEncoder.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/UpdateAddressStatusRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/UpdateShelterPasswordRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfo.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/security/jwt/JJwtProvider.java
  src/main/java/com/clova/anifriends/global/security/passwordencoder/BCryptCustomPasswordEncoder.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
  src/test/java/com/clova/anifriends/domain/auth/support/MockPasswordEncode.java
  src/test/java/com/clova/anifriends/domain/auth/support/MockPasswordEncoder.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/support/ShelterFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPasswordTest.java
  src/test/java/com/clova/anifriends/global/security/BCryptCustomPasswordEncoderTest.java
Labels: ✨ Feat

#170 feat: 비밀번호를 변경한다.(보호소)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/support/ShelterFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPasswordTest.java
Labels: ✨ Feat

#173 feat: 계정 정보를 수정한다.(봉사자)
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsApprovedResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsResponse.java
  src/main/java/com/clova/anifriends/domain/common/ImageRemover.java
  src/main/java/com/clova/anifriends/domain/common/MockImageRemover.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/request/UpdateVolunteerInfoRequest.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/FindVolunteerMyPageResponse.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerName.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumber.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/base/MockImageRemover.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
Labels: ✨ Feat

#174 feat: 봉사 모집글을 마감한다.(보호소)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfoTest.java
Labels: ✨ Feat

#171 feat: 봉사자 출석 상태 수정 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/request/UpdateApplicantsAttendanceRequest.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApplicantsApprovedResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApplyingVolunteersResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/applicant/service/dto/UpdateApplicantAttendanceCommand.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/applicant/support/ApplicantFixture.java
Labels: ✨ Feat

#175 refactor: 회원가입(봉사자) 로직에 패스워드 인코딩을 추가한다.
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPasswordTest.java
Labels: 🔨 Refactor

#176 feat: 비밀번호 변경(봉사자) 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/request/UpdateVolunteerPasswordRequest.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPasswordTest.java
Labels: ✨ Feat

#177 feat: 보호동물 입양 상태 변경 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/UpdateAnimalAdoptStatusRequest.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalAdopted.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalNeutered.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalFixture.java
  src/test/java/com/clova/anifriends/domain/animal/wrapper/AnimalAdoptedTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImplTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
Labels: ✨ Feat

#179 feat: 계정 정보 수정 기능을 구현한다.(보호소)
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalDetail.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentDetailResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindReviewResponse.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindVolunteerReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/ShelterImage.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/request/CheckDuplicateShelterEmailRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/request/RegisterShelterRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/request/UpdateAddressStatusRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/request/UpdateShelterPasswordRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/request/UpdateShelterRequest.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/response/CheckDuplicateShelterResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/response/FindShelterDetailResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/response/FindShelterMyPageResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/response/FindShelterSimpleByVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfo.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterName.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfo.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/support/ReviewDtoFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/support/ShelterFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfoTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterNameTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfoTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
Labels: ✨ Feat

#181 feat: 봉사 신청 상태를 수정(승인/거절)한다.(보호소)
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/request/UpdateApplicantStatusRequest.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
Labels: ✨ Feat

#185 feat: 봉사 후기를 수정한다.(봉사자)
  src/main/java/com/clova/anifriends/domain/common/ImageRemover.java
  src/main/java/com/clova/anifriends/domain/common/MockImageRemover.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/request/UpdateReviewRequest.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/review/wrapper/ReviewContent.java
  src/test/java/com/clova/anifriends/base/MockImageRemover.java
  src/test/java/com/clova/anifriends/domain/review/ReviewTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feat

#180 feat: S3 이미지 삭제 서비스를 구현한다.
  src/main/java/com/clova/anifriends/global/config/S3Config.java
  src/main/java/com/clova/anifriends/global/image/S3Service.java
  src/test/java/com/clova/anifriends/global/image/S3ServiceTest.java
Labels: ✨ Feat

#178 feat: 봉사 모집글을 수정한다.(보호소)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/common/ImageRemover.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentContent.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTitle.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentContentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfoTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTitleTest.java
Labels: ✨ Feat

#183 refactor: 권한에 따른 API URI 경로를 개선한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsRequest.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsResponse.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/response/FindShelterSimpleResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: 🔨 Refactor

#203 chore: cors 설정을 추가한다.
  src/main/java/com/clova/anifriends/global/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#199 feat: 보호 동물 삭제 API를 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/animal/AnimalTest.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
Labels: ✨ Feat

#200 feat: 봉사 후기 삭제 API를 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/ReviewTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feat

#202 feat: 봉사 모집글 삭제 API를 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfo.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentInfoTest.java
Labels: ✨ Feat

#209 feat: 보호소가 받은 후기 리스트 조회(보호소) api 응답 필드를 추가한다.
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
Labels: ✨ Feat

#216 feat: 채팅 관련 Entity, Controller, Service, Repository 를 생성한다.
  build.gradle
  src/main/java/com/clova/anifriends/domain/chat/ChatMessage.java
  src/main/java/com/clova/anifriends/domain/chat/ChatRoom.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatService.java
  src/main/java/com/clova/anifriends/global/config/WebSocketConfig.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
Labels: ✨ Feat

#218 feat: 알림 도메인을 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/ShelterNotification.java
  src/main/java/com/clova/anifriends/domain/notification/VolunteerNotification.java
  src/main/java/com/clova/anifriends/domain/notification/exception/NotificationBadRequestException.java
  src/main/java/com/clova/anifriends/domain/notification/wrapper/NotificationContent.java
  src/main/java/com/clova/anifriends/domain/notification/wrapper/NotificationRead.java
  src/main/java/com/clova/anifriends/domain/notification/wrapper/NotificationTitle.java
  src/main/java/com/clova/anifriends/domain/notification/wrapper/NotificationType.java
  src/test/java/com/clova/anifriends/domain/notification/ShelterNotificationTest.java
  src/test/java/com/clova/anifriends/domain/notification/VolunteerNotificationTest.java
  src/test/java/com/clova/anifriends/domain/notification/wrapper/NotificationContentTest.java
  src/test/java/com/clova/anifriends/domain/notification/wrapper/NotificationReadTest.java
  src/test/java/com/clova/anifriends/domain/notification/wrapper/NotificationTitleTest.java
Labels: ✨ Feat

#226 feat: 인증 객체 principal에 역할 필드를 추가한다.
  src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthentication.java
  src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProvider.java
  src/main/java/com/clova/anifriends/domain/auth/dto/response/CustomClaims.java
  src/main/java/com/clova/anifriends/global/security/jwt/JJwtProvider.java
  src/main/java/com/clova/anifriends/global/web/argumentresolver/LoginUserArgumentResolver.java
  src/test/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProviderTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserArgumentResolverTest.java
  src/test/java/com/clova/anifriends/domain/auth/resolver/LoginUserTestController.java
Labels: ✨ Feat

#229 feat: 채팅방 생성 기능을 구현한다.
  src/main/java/com/clova/anifriends/domain/chat/ChatRoom.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/request/RegisterChatRoomRequest.java
  src/main/java/com/clova/anifriends/domain/chat/exception/ChatRoomBadRequestException.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatService.java
  src/main/java/com/clova/anifriends/global/config/WebSocketConfig.java
  src/test/java/com/clova/anifriends/domain/chat/ChatRoomTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatServiceTest.java
Labels: ✨ Feat

#227 feat: 보호소 알림 조회 API를 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/ShelterNotification.java
  src/main/java/com/clova/anifriends/domain/notification/VolunteerNotification.java
  src/main/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/dto/response/FindShelterNotificationsResponse.java
  src/main/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepository.java
  src/main/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepository.java
  src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
  src/test/java/com/clova/anifriends/domain/notification/support/fixture/ShelterNotificationFixture.java
Labels: ✨ Feat

#223 feat: 채팅방 상세 조회 로직을 구현한다.(봉사자)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/chat/ChatMessage.java
  src/main/java/com/clova/anifriends/domain/chat/ChatRoom.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/FindChatRoomDetailResponse.java
  src/main/java/com/clova/anifriends/domain/chat/exception/ChatNotFoundException.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/clova/anifriends/domain/chat/support/ChatRoomFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
Labels: ✨ Feat

#230 feat: 봉사자 알림 조회 API를 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/dto/FindVolunteerNotificationsResponse.java
  src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationServiceTest.java
  src/test/java/com/clova/anifriends/domain/notification/support/fixture/VolunteerNotificationFixture.java
Labels: ✨ Feat

#232 feat: 보호소 새로운 알림 여부 조회 API를 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/dto/response/FindShelterHasNewNotificationResponse.java
  src/main/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepository.java
  src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java
  src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
Labels: ✨ Feat

#235 feat: 새로운 채팅방에서 메시지 발생 시 메시지를 publish 한다.
  src/main/java/com/clova/anifriends/domain/chat/ChatMessage.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java
  src/main/java/com/clova/anifriends/domain/chat/exception/ChatMessageBadRequestException.java
  src/main/java/com/clova/anifriends/domain/chat/exception/ChatRoomNotFoundException.java
  src/main/java/com/clova/anifriends/domain/chat/message/pub/NewChatMessagePub.java
  src/main/java/com/clova/anifriends/domain/chat/message/sub/ChatMessageSub.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatMessageService.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/ChatMessageTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/WebSocketStompTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatMessageServiceTest.java
  src/test/java/com/clova/anifriends/domain/chat/support/ChatMessageFixture.java
Labels: ✨ Feat

#234 feat: 채팅방 목록 조회 로직을 구현한다.(봉사자)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/FindChatRoomsResponse.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/clova/anifriends/domain/chat/repository/response/FindChatRoomResult.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomMapper.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/clova/anifriends/domain/chat/support/ChatRoomDtoFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/support/ShelterFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
Labels: ✨ Feat

#233 feat: 봉사자 새로운 알림 여부 조회 API를 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/dto/response/FindVolunteerHasNewNotificationResponse.java
  src/main/java/com/clova/anifriends/domain/notification/dto/response/FindVolunteerNotificationsResponse.java
  src/main/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepository.java
  src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java
  src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationServiceTest.java
Labels: ✨ Feat

#238 feat: 보호소 알림 읽음 처리 API를 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepository.java
  src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java
  src/test/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/repository/ShelterNotificationRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
Labels: ✨ Feat

#242 feat: 기존 채팅방에서 새로운 메시지 발생 시 메시지를 publish 한다.
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageResponse.java
  src/main/java/com/clova/anifriends/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/NewChatMessageResponse.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatMessageService.java
  src/test/java/com/clova/anifriends/domain/chat/controller/WebSocketStompTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatMessageServiceTest.java
Labels: ✨ Feat

#247 feat: 채팅방ID를 조회하는 기능을 구현한다.
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/FindChatRoomIdResponse.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/clova/anifriends/domain/chat/support/ChatRoomFixture.java
Labels: ✨ Feat

#248 refactor: S3 이미지 삭제 로직을 서비스에서 하도록 수정한다.
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/domain/common/ImageRemover.java
  src/main/java/com/clova/anifriends/domain/common/MockImageRemover.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/main/java/com/clova/anifriends/global/image/S3Service.java
  src/test/java/com/clova/anifriends/base/MockImageRemover.java
  src/test/java/com/clova/anifriends/domain/animal/AnimalTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/RecruitmentTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
  src/test/java/com/clova/anifriends/domain/review/ReviewTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/support/ReviewFixture.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
Labels: 🔨 Refactor

#245 feat: 채팅방 목록 조회 로직을 구현한다.(보호소)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomMapper.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
Labels: ✨ Feat

#240 feat: 봉사자 알림 읽음 처리 API를 구현한다.
  src/main/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepository.java
  src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java
  src/test/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationControllerTest.java
  src/test/java/com/clova/anifriends/domain/notification/repository/VolunteerNotificationRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationServiceTest.java
Labels: ✨ Feat

#249 feat: 채팅방 상세 조회 로직을 구현한다.(보호소)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/FindChatRoomDetailResponse.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
Labels: ✨ Feat

#252 feat: 로그 aop 와 logback 설정 파일을 추가한다.
  .gitignore
  build.gradle
  src/main/java/com/clova/anifriends/global/aspect/LogAspect.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feat

#258 feat: 스프링 시큐리티 역할 기반 api 필터링 시 응답 메시지 내용을 커스텀한다.
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/security/authorize/UnauthorizedEntryPoint.java
  src/test/java/com/clova/anifriends/global/security/authorize/UnauthorizedEntryPointTest.java
Labels: ✨ Feat

#255 feat: 로그인 시 클라이언트로부터 fcm token을 받는다.
  src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
  src/main/java/com/clova/anifriends/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterDeviceToken.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerDeviceToken.java
  src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/shelter/wrapper/ShelterDeviceTokenTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerDeviceTokenTest.java
Labels: ✨ Feat

#259 feat: 비밀번호 변경 시 실패에 대한 에러코드를 추가한다.
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java
  src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
Labels: ✨ Feat

#261 feat: 안읽은 메시지 총 개수를 조회한다.(보호소)
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomServiceTest.java
Labels: ✨ Feat

#264 refactor: 봉사자 비밀번호 변경 API 경로를 수정한다.
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: 🔨 Refactor

#266 refactor: jpql 의 where 문에서 Enum 을 사용하도록 수정한다.
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
Labels: 🔨 Refactor

#286 feat: 보호소 모집 검색 API에서 마감 여부 필터링을 추가한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: ✨ Feat

#282 refactor: 봉사 모집글 조회 마감 여부 필터를 enum 값으로 변경한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentStatusFilter.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsRequest.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 🔨 Refactor

#287 refactor: 봉사 모집글 조회 키워드 필터를 enum으로 변경한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/KeywordCondition.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/KeywordConditionByShelter.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/KeywordFilter.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsRequest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/KeywordFilterTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
Labels: 🔨 Refactor

#288 fix: 프론트엔드 연동 시 403을 반환하는 문제를 해결한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/auth/authorization/ShelterOnly.java
  src/main/java/com/clova/anifriends/domain/auth/authorization/UserOnly.java
  src/main/java/com/clova/anifriends/domain/auth/authorization/VolunteerOnly.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/notification/controller/ShelterNotificationController.java
  src/main/java/com/clova/anifriends/domain/notification/controller/VolunteerNotificationController.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/exception/GlobalExceptionHandler.java
  src/main/java/com/clova/anifriends/global/security/authorize/UnauthorizedEntryPoint.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/global/exception/ExceptionController.java
  src/test/java/com/clova/anifriends/global/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/clova/anifriends/global/security/authorize/UnauthorizedEntryPointTest.java
Labels: 🐞 Bug

#284 refactor: 보호 동물 목록 조회 시 중성화 필터링 Enum 을 사용한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByVolunteerRequest.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/domain/animal/vo/AnimalNeuteredFilter.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
Labels: 🔨 Refactor

#289 feat: unique 제약조건을 설정하고 AOP를 통해 예외를 핸들링한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/chat/ChatRoom.java
  src/main/java/com/clova/anifriends/domain/chat/exception/ChatRoomConflictException.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/exception/ReviewConflictException.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/review/vo/ReviewContent.java
  src/main/java/com/clova/anifriends/global/aspect/DataIntegrityAspect.java
  src/main/java/com/clova/anifriends/global/aspect/DataIntegrityHandler.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/chat/support/ChatRoomFixture.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
Labels: ✨ Feat

#293 refactor: 봉사 모집글 검색(봉사자) 로직의 페이지네이션을 커서 기반으로 개선한다.
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/request/FindRecruitmentsRequestV2.java
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: 🔨 Refactor

#292 feat: 봉사 모집글 상세 조회 API에 shelterId를 추가한다.
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentDetailResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: ✨ Feat

#296 fix: 봉사 모집글 목록 조회시 마감 시간을 api 응답에 추가한다.
  src/main/java/com/clova/anifriends/domain/recruitment/dto/response/FindRecruitmentsResponse.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
Labels: 🐞 Bug

#294 refactor: 보호동물 검색(봉사자) 로직의 페이지네이션을 커서 기반으로 개선한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/FindAnimalsByVolunteerRequestV2.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
Labels: 🔨 Refactor

#297 refactor: 봉사 신청 로직 동시성 이슈를 해결한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/domain/recruitment/vo/RecruitmentApplicantCount.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/support/fixture/RecruitmentFixture.java
  src/test/java/com/clova/anifriends/domain/recruitment/vo/RecruitmentApplicantCountTest.java
Labels: 🔨 Refactor

#304 fix: 인증 필터 예외 핸들링을 추가한다.
  src/main/java/com/clova/anifriends/domain/auth/authentication/JwtAuthenticationProvider.java
  src/main/java/com/clova/anifriends/global/config/SecurityConfig.java
  src/main/java/com/clova/anifriends/global/security/jwt/JJwtProvider.java
  src/main/java/com/clova/anifriends/global/web/filter/JwtAuthenticationExceptionHandler.java
  src/main/java/com/clova/anifriends/global/web/filter/JwtAuthenticationFilter.java
  src/test/java/com/clova/anifriends/global/web/filter/JwtAuthenticationExceptionHandlerTest.java
Labels: 🐞 Bug

#303 refactor: findRecruitmentDetail의 n+1 문제를 fetch join으로 해결한다.
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
Labels: 🔨 Refactor

#311 refactor: 프로필 이미지 수정 시 null 대신 빈 문자열을 다루도록 개선한다.
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/test/java/com/clova/anifriends/domain/shelter/ShelterTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
Labels: 🔨 Refactor

#312 feat: 리소스 생성시 응답 바디에 리소스 ID를 함께 반환하도록 변경한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatRoomController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/RegisterChatRoomResponse.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatRoomService.java
  src/main/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/clova/anifriends/domain/review/controller/ReviewController.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/RegisterReviewResponse.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/shelter/controller/ShelterController.java
  src/main/java/com/clova/anifriends/domain/shelter/dto/response/RegisterShelterResponse.java
  src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/response/RegisterVolunteerResponse.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/controller/RecruitmentControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
Labels: ✨ Feat

#319 feat: 보호동물 목록 조회 시 첫 페이지 정보를 캐싱한다.
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalCacheRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/java/com/clova/anifriends/global/config/RedisConfig.java
  src/main/java/com/clova/anifriends/global/event/CacheWarmer.java
  src/test/java/com/clova/anifriends/AnifriendsApplicationTests.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/base/TestContainerStarter.java
  src/test/java/com/clova/anifriends/base/config/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalDtoFixture.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalFixture.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/WebSocketStompTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
Labels: ✨ Feat

#321 fix: 보호 동물 목록 조회 dto 의 보호 동물 크기 파라미터명을 animalSize 로 변경한다.
  src/main/java/com/clova/anifriends/domain/animal/controller/AnimalController.java
  src/main/java/com/clova/anifriends/domain/animal/dto/FindAnimalsByVolunteerRequestV2.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByShelterRequest.java
  src/main/java/com/clova/anifriends/domain/animal/dto/request/FindAnimalsByVolunteerRequest.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java
Labels: 🐞 Bug

#318 refactor: 봉사자 입장에서 모집글 검색 시 count를 캐시에 저장한다.
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheService.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/clova/anifriends/global/config/RedisConfig.java
  src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatRoomIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentCacheServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/shelter/service/ShelterIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerIntegrationTest.java
Labels: 🔨 Refactor

#322 feat: 리뷰 작성 시 봉사자 온도를 상승한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/vo/VolunteerTemperature.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/vo/VolunteerTemperatureTest.java
Labels: ✨ Feat

#324 feat: 봉사자 입장에서 보호동물 목록 조회 시 count를 캐시에 저장한다.
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalCacheRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalCacheServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
Labels: ✨ Feat

#327 feat: 봉사자의 출석 변경에 따른 온도 증감 로직을 추가한다.
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/recruitment/vo/RecruitmentInfo.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
  src/main/java/com/clova/anifriends/domain/volunteer/vo/VolunteerTemperature.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/vo/VolunteerTemperatureTest.java
Labels: ✨ Feat

#325 fix: 리프레시 토큰이 존재하지 않는 경우에 대한 예외를 추가한다.
  src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
  src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
  src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
Labels: 🐞 Bug

#335 docs: notification 관련 문서화를 추가한다.
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
Labels: 📝 Docs

#338 docs: Volunteer 관련 문서화를 추가한다.
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
Labels: 📝 Docs

#347 refactor: 채팅 기능의 SimpleMessage 브로커를 Redis pub/sub 기반의 브로커로 변경한다.
  src/main/java/com/clova/anifriends/domain/chat/controller/ChatMessageController.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/clova/anifriends/domain/chat/dto/response/NewChatMessageResponse.java
  src/main/java/com/clova/anifriends/domain/chat/exception/MessageJsonMappingException.java
  src/main/java/com/clova/anifriends/domain/chat/service/ChatMessageService.java
  src/main/java/com/clova/anifriends/domain/chat/service/MessagePublisher.java
  src/main/java/com/clova/anifriends/domain/chat/service/MessageSubscriber.java
  src/main/java/com/clova/anifriends/global/config/RedisConfig.java
  src/main/java/com/clova/anifriends/global/exception/JsonMappingException.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/chat/controller/WebSocketStompTest.java
  src/test/java/com/clova/anifriends/domain/chat/service/ChatMessageServiceTest.java
  src/test/java/com/clova/anifriends/domain/chat/support/ChatMessageFixture.java
  src/test/resources/application.yml
Labels: 🔨 Refactor

#343 feat: 스케줄러 사용 알림을 적용한다.
  build.gradle
  src/main/java/com/clova/anifriends/AnifriendsApplication.java
  src/main/java/com/clova/anifriends/domain/notification/service/ShelterNotificationService.java
  src/main/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationService.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/notification/service/NotificationScheduledTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/ShelterNotificationServiceTest.java
  src/test/java/com/clova/anifriends/domain/notification/service/VolunteerNotificationServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepositoryTest.java
  src/test/resources/application.yml
Labels: ✨ Feat

#356 refactor: 봉사자가 작성한 후기 리스트(봉사자), 봉사자가 작성한 후기 리스트(보호소) response에 shelterId를 추가한다.
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindVolunteerReviewsResponse.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
Labels: 🔨 Refactor

#354 docs: readme를 작성한다.
  README.md
Labels: 📝 Docs

#353 feat: 로그아웃 기능을 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/auth/controller/AuthController.java
  src/main/java/com/clova/anifriends/domain/auth/service/AuthService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
  src/test/java/com/clova/anifriends/domain/auth/support/AuthFixture.java
Labels: ✨ Feat

#359 refactor: 봉사자가 신청한 봉사 리스트 조회를 pagination 방식으로 변경한다.
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApplyingVolunteersResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/applicant/vo/ApplicantStatus.java
  src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
Labels: 🔨 Refactor

#358 refactor: N+1 문제가 발생하는 곳을 개선한다.
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplicantsResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApplyingVolunteersResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/response/FindApplicantResult.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/response/FindApplyingVolunteerResult.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantMapper.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/test/java/com/clova/anifriends/domain/applicant/ApplicantTest.java
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantMapperTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/applicant/support/ApplicantDtoFixture.java
Labels: 🔨 Refactor

#363 refactor: findApplyingVolunteers에서 ApplicantStatus를 반환하는 로직을 변경한다.
  src/main/java/com/clova/anifriends/domain/applicant/dto/response/FindApplyingVolunteersResponse.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantMapper.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/applicant/vo/ApplicantStatus.java
  src/test/java/com/clova/anifriends/domain/applicant/vo/ApplicantStatusTest.java
Labels: 🔨 Refactor

#368 feat: 봉사 신청 여부 조회 API를 추가한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/service/ApplicantService.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/IsAppliedRecruitmentResponse.java
  src/main/java/com/clova/anifriends/domain/recruitment/service/RecruitmentService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/clova/anifriends/domain/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/applicant/service/ApplicantServiceTest.java
  src/test/java/com/clova/anifriends/domain/recruitment/service/RecruitmentServiceTest.java
Labels: ✨ Feat

#362 refactor: 보호 동물 조회 api 에서 발생한 N+1 문제를 해결한다.
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/dto/response/FindAnimalsResponse.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalCacheRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryCustom.java
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryImpl.java
  src/main/java/com/clova/anifriends/domain/animal/repository/response/FindAnimalsResult.java
  src/main/java/com/clova/anifriends/domain/animal/service/AnimalService.java
  src/test/java/com/clova/anifriends/domain/animal/controller/AnimalControllerTest.java
  src/test/java/com/clova/anifriends/domain/animal/repository/AnimalRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceIntegrationTest.java
  src/test/java/com/clova/anifriends/domain/animal/service/AnimalServiceTest.java
  src/test/java/com/clova/anifriends/domain/animal/support/fixture/AnimalDtoFixture.java
Labels: 🔨 Refactor

#364 feat: findShelterReviewsByShelter의 n+1 문제를 개선한다.
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/dto/response/FindShelterReviewsByShelterResponse.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/review/repository/response/FindShelterReviewResult.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewMapper.java
  src/main/java/com/clova/anifriends/domain/review/service/ReviewService.java
  src/test/java/com/clova/anifriends/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/clova/anifriends/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/clova/anifriends/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clova/anifriends/domain/review/support/ReviewDtoFixture.java
Labels: ✨ Feat

#371 chore: 불필요한 CI 워크플로우를 제거한다.
  .github/workflows/CI.yml
  .github/workflows/ci.yml
Labels: ⚙ Setting

#372 feat: nginx에 파일 용량 제한을 늘린다.
  nginx/nginx.conf
Labels: ✨ Feat
