Repository anifriends/Anifriends-Backend, pull requests merged in 2023-10, with the labels that each got.

#4 chore: 통합 테스트를 위한 테스트 환경을 세팅한다.
  .github/workflows/auto-reviewer.yml
  anifriends/src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  anifriends/src/test/java/com/clova/anifriends/base/BaseIntegrationTest.java
  anifriends/src/test/java/com/clova/anifriends/base/BaseRepositoryTest.java
  anifriends/src/test/java/com/clova/anifriends/base/DatabaseCleaner.java
Labels: ⚙ Setting, ✅ Test

#5 chore: SpringRestDocs 추가 및 커스텀한다.
  anifriends/build.gradle
  anifriends/src/main/java/com/clova/anifriends/EnumType.java
  anifriends/src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  anifriends/src/test/java/com/clova/anifriends/base/config/RestDocsConfig.java
  anifriends/src/test/java/com/clova/anifriends/docs/enumtype/EnumDocsController.java
  anifriends/src/test/java/com/clova/anifriends/docs/enumtype/EnumDocumentationTest.java
  anifriends/src/test/java/com/clova/anifriends/docs/enumtype/EnumResponseFieldsSnippet.java
  anifriends/src/test/java/com/clova/anifriends/docs/enumtype/TestEnum.java
  anifriends/src/test/java/com/clova/anifriends/docs/format/DocumentationFormatGenerator.java
  anifriends/src/test/java/com/clova/anifriends/docs/format/DocumentationTest.java
  anifriends/src/test/java/com/clova/anifriends/docs/format/DocumentationTestController.java
  anifriends/src/test/java/com/clova/anifriends/docs/format/TestRequest.java
  anifriends/src/test/resources/org/springframework/restdocs/templates/enum-response-fields.snippet
  anifriends/src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  anifriends/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: ⚙ Setting, 📝 Docs

#15 chore: 모든 파일에 대한 CODEOWNERS 를 설정한다.
  .github/CODEOWNERS
  .github/workflows/auto-reviewer.yml
Labels: ⚙ Setting

#12 chore: QueryDSL 세팅한다.
  anifriends/.gitignore
  anifriends/build.gradle
Labels: ⚙ Setting

#16 feat: Entity를 구현한다.
  anifriends/src/main/java/com/clova/anifriends/domain/animal/Animal.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/AnimalImage.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Active.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Breed.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Gender.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Information.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/IsNeutered.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Name.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Type.java
  anifriends/src/main/java/com/clova/anifriends/domain/animal/wrapper/Weight.java
  anifriends/src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  anifriends/src/main/java/com/clova/anifriends/domain/applicant/wrapper/Status.java
  anifriends/src/main/java/com/clova/anifriends/domain/common/BaseTimeEntity.java
  anifriends/src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  anifriends/src/main/java/com/clova/anifriends/domain/recruitment/RecruitmentImage.java
  anifriends/src/main/java/com/clova/anifriends/domain/recruitment/wrapper/Capacity.java
  anifriends/src/main/java/com/clova/anifriends/domain/recruitment/wrapper/Content.java
  anifriends/src/main/java/com/clova/anifriends/domain/recruitment/wrapper/IsClosed.java
  anifriends/src/main/java/com/clova/anifriends/domain/recruitment/wrapper/Title.java
  anifriends/src/main/java/com/clova/anifriends/domain/review/Review.java
  anifriends/src/main/java/com/clova/anifriends/domain/review/ReviewImage.java
  anifriends/src/main/java/com/clova/anifriends/domain/review/wrapper/Content.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/ShelterImage.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/Address.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/AddressDetail.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/Email.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/IsOpenedAddress.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/Name.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/Password.java
  anifriends/src/main/java/com/clova/anifriends/domain/shelter/wrapper/PhoneNumber.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/wrapper/Email.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/wrapper/Gender.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/wrapper/Name.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/wrapper/Password.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/wrapper/PhoneNumber.java
  anifriends/src/main/java/com/clova/anifriends/domain/volunteer/wrapper/Temperature.java
Labels: ✨ Feat

#18 chore: 소나클라우드와 프로젝트를 연결한다.
  .github/workflows/ci.yml
  build.gradle
Labels: ⚙ Setting

#21 chore: CD를 설정한다.
  .github/workflows/CD.yml
  appspec.yml
  scripts/deploy.sh
Labels: ⚙ Setting, 🚀 CI/CD

#22 refactor: 엔티티를 개선한다.
  src/main/java/com/clova/anifriends/domain/animal/Animal.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalActive.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalBreed.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalGender.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalInformation.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalName.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalNeutered.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalType.java
  src/main/java/com/clova/anifriends/domain/animal/wrapper/AnimalWeight.java
  src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
  src/main/java/com/clova/anifriends/domain/applicant/wrapper/ApplicantStatus.java
  src/main/java/com/clova/anifriends/domain/recruitment/Recruitment.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/Capacity.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/IsClosed.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentContent.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentDeadlineInfo.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTime.java
  src/main/java/com/clova/anifriends/domain/recruitment/wrapper/RecruitmentTitle.java
  src/main/java/com/clova/anifriends/domain/review/Review.java
  src/main/java/com/clova/anifriends/domain/review/wrapper/ReviewContent.java
  src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/Address.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/AddressDetail.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/IsOpenedAddress.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/PhoneNumber.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterAddressInfo.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterEmail.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterName.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPassword.java
  src/main/java/com/clova/anifriends/domain/shelter/wrapper/ShelterPhoneNumberInfo.java
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerEmail.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerGender.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerName.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumber.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerTemperature.java
Labels: 🔨 Refactor

#24 feat: repository 를 구현한다.
  src/main/java/com/clova/anifriends/domain/animal/repository/AnimalRepository.java
  src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
  src/main/java/com/clova/anifriends/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/clova/anifriends/domain/review/repository/ReviewRepository.java
  src/main/java/com/clova/anifriends/domain/shelter/repository/ShelterRepository.java
  src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
Labels: ✨ Feat

#32 fix: jacoco 테스트 커버리지 측정하도록 수정
  build.gradle
Labels: 🐞 Bug

#40 feat: Exception에 예외코드를 추가한다.
  src/main/java/com/clova/anifriends/global/exception/AniFriendsException.java
  src/main/java/com/clova/anifriends/global/exception/AuthenticationException.java
  src/main/java/com/clova/anifriends/global/exception/AuthorizationException.java
  src/main/java/com/clova/anifriends/global/exception/BadRequestException.java
  src/main/java/com/clova/anifriends/global/exception/ConflictException.java
  src/main/java/com/clova/anifriends/global/exception/ErrorCode.java
  src/main/java/com/clova/anifriends/global/exception/ErrorResponse.java
  src/main/java/com/clova/anifriends/global/exception/GlobalExceptionHandler.java
  src/main/java/com/clova/anifriends/global/exception/NotFoundException.java
  src/test/java/com/clova/anifriends/global/exception/ExceptionController.java
Labels: ✨ Feat

#38 feat: 봉사자 회원가입 로직을 구현한다.
  src/main/java/com/clova/anifriends/domain/volunteer/Volunteer.java
  src/main/java/com/clova/anifriends/domain/volunteer/VolunteerImage.java
  src/main/java/com/clova/anifriends/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/clova/anifriends/domain/volunteer/dto/request/RegisterVolunteerRequest.java
  src/main/java/com/clova/anifriends/domain/volunteer/exception/NotFoundVolunteerGenderException.java
  src/main/java/com/clova/anifriends/domain/volunteer/exception/VolunteerBadRequestException.java
  src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerImageRepository.java
  src/main/java/com/clova/anifriends/domain/volunteer/service/VolunteerService.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerEmail.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerGender.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerName.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPassword.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumber.java
  src/main/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerTemperature.java
  src/test/java/com/clova/anifriends/base/BaseControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/VolunteerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/controller/VolunteerControllerTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/service/VolunteerServiceTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerDtoFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/support/VolunteerFixture.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerEmailTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerGenderTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerNameTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPasswordTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerPhoneNumberTest.java
  src/test/java/com/clova/anifriends/domain/volunteer/wrapper/VolunteerTemperatureTest.java
Labels: ✨ Feat
